FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    iputils-ping \
    iproute2 \
    net-tools \
    curl \
    wget \
    nmap \
    netcat \
    tcpdump \
    dnsutils \
    vim \
    nano \
    apache2 \
    iptables \ 
    sqlmap \ 
    python3 \
    python3-utils \ 
    && rm -rf /var/lib/apt/lists/*

WORKDIR /root

CMD ["/bin/bash"]
